services:
  sbexplorer.mud:
    image: sbexplorer.mud
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
        - "ServiceBus__ConnectionString=Endpoint=sb://servicebus-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
        - "ServiceBus_RefreshIntervalMs=5000"
        - "Redis__ConnectionString=redis:6379,abortConnect=false,ssl=false,password=pass@w0rd1"
        - "ASPNETCORE_ENVIRONMENT=Production"
        - "ASPNETCORE_URLS=https://+:443;http://+:80"
        - "ASPNETCORE_Kestrel__Certificates__Default__Password=password"
        - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
        sb-emulator:
            aliases:
                - "sbexplorer.mud"
  servicebus-emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - "${CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: sql
      MSSQL_SA_PASSWORD: "${SQL_PASSWORD}"  # Password should be same as what is set for SQL
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      - sql
    networks:
      sb-emulator:
        aliases:
          - "serivcebus-emulator"
  sql:
    container_name: "sql"
    image: "mcr.microsoft.com/mssql/server:latest"
    networks:
      sb-emulator:
        aliases:
          - "sql"
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: "${SQL_PASSWORD}"
  redis:
    image: redis:8.0-M02-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass pass@w0rd1
    volumes:
      - ./data:/data
    networks:
      sb-emulator:
        aliases:
          - "redis"
networks:
  sb-emulator:
