services:
  sb-explorer:
    image: ghcr.io/tombiddulph/sbuitest:latest
#    build:
#      context: .
#      dockerfile: src/ServiceBusEmulatorExplorer/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - "ServiceBus__ConnectionString=Endpoint=sb://servicebus-emulator;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
      - "ServiceBus__AdministrationConnectionString=Endpoint=sb://servicebus-emulator:5300;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
      - "ServiceBus_RefreshIntervalMs=5000"
      - "ASPNETCORE_ENVIRONMENT=Production"
    networks:
      sb-emulator:
        aliases:
          - "sb-explorer"
  servicebus-emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
  
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      SQL_SERVER: sql
      MSSQL_SA_PASSWORD: "${SQL_PASSWORD}"  # Password should be same as what is set for SQL
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      - sql
    networks:
      sb-emulator:
        aliases:
          - "serivcebus-emulator"
  sql:
    container_name: "sql"
    image: "mcr.microsoft.com/mssql/server:latest"
    networks:
      sb-emulator:
        aliases:
          - "sql"
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: "${SQL_PASSWORD}"
networks:
  sb-emulator:

